# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import suggestion_service_pb2 as suggestion__service__pb2


class SuggestionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MakeSuggestion = channel.unary_unary(
                '/suggestion_service.Suggestion/MakeSuggestion',
                request_serializer=suggestion__service__pb2.SuggestionRequest.SerializeToString,
                response_deserializer=suggestion__service__pb2.SuggestionResponse.FromString,
                )


class SuggestionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MakeSuggestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SuggestionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MakeSuggestion': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeSuggestion,
                    request_deserializer=suggestion__service__pb2.SuggestionRequest.FromString,
                    response_serializer=suggestion__service__pb2.SuggestionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'suggestion_service.Suggestion', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Suggestion(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MakeSuggestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/suggestion_service.Suggestion/MakeSuggestion',
            suggestion__service__pb2.SuggestionRequest.SerializeToString,
            suggestion__service__pb2.SuggestionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
