# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import suggestion_service_pb2 as suggestion__service__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in suggestion_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SuggestionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MakeSuggestion = channel.unary_unary(
                '/suggestion_service.Suggestion/MakeSuggestion',
                request_serializer=suggestion__service__pb2.SuggestionRequest.SerializeToString,
                response_deserializer=suggestion__service__pb2.SuggestionResponse.FromString,
                _registered_method=True)
        self.InitOrder = channel.unary_unary(
                '/suggestion_service.Suggestion/InitOrder',
                request_serializer=suggestion__service__pb2.InitSuggestionRequest.SerializeToString,
                response_deserializer=suggestion__service__pb2.InitSuggestionResponse.FromString,
                _registered_method=True)


class SuggestionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MakeSuggestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SuggestionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MakeSuggestion': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeSuggestion,
                    request_deserializer=suggestion__service__pb2.SuggestionRequest.FromString,
                    response_serializer=suggestion__service__pb2.SuggestionResponse.SerializeToString,
            ),
            'InitOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.InitOrder,
                    request_deserializer=suggestion__service__pb2.InitSuggestionRequest.FromString,
                    response_serializer=suggestion__service__pb2.InitSuggestionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'suggestion_service.Suggestion', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('suggestion_service.Suggestion', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Suggestion(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MakeSuggestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/suggestion_service.Suggestion/MakeSuggestion',
            suggestion__service__pb2.SuggestionRequest.SerializeToString,
            suggestion__service__pb2.SuggestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/suggestion_service.Suggestion/InitOrder',
            suggestion__service__pb2.InitSuggestionRequest.SerializeToString,
            suggestion__service__pb2.InitSuggestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
