# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction_verification/transaction_verification.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

import sys
import os
original_sys_path = list(sys.path)

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from order_data import order_pb2 as order__data_dot_order__pb2

sys.path = original_sys_path

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7transaction_verification/transaction_verification.proto\x12\x0cverification\x1a\x16order_data/order.proto\";\n\x13VerificationRequest\x12$\n\norder_data\x18\x01 \x01(\x0b\x32\x10.order.OrderData\"(\n\x14VerificationResponse\x12\x10\n\x08response\x18\x01 \x01(\t2q\n\x13VerificationService\x12Z\n\x11VerifyTransaction\x12!.verification.VerificationRequest\x1a\".verification.VerificationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_verification.transaction_verification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VERIFICATIONREQUEST']._serialized_start=97
  _globals['_VERIFICATIONREQUEST']._serialized_end=156
  _globals['_VERIFICATIONRESPONSE']._serialized_start=158
  _globals['_VERIFICATIONRESPONSE']._serialized_end=198
  _globals['_VERIFICATIONSERVICE']._serialized_start=200
  _globals['_VERIFICATIONSERVICE']._serialized_end=313
# @@protoc_insertion_point(module_scope)
