# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction_verification.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'transaction_verification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
import order_pb2 as order__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etransaction_verification.proto\x12\x0cverification\x1a\x0c\x63ommon.proto\x1a\x0border.proto\"\'\n\x13VerificationRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"S\n\x14VerificationResponse\x12\x10\n\x08response\x18\x01 \x01(\t\x12)\n\x0cvector_clock\x18\x02 \x01(\x0b\x32\x13.common.VectorClock\"8\n\x10InitOrderRequest\x12$\n\norder_data\x18\x01 \x01(\x0b\x32\x10.order.OrderData\"#\n\x11InitOrderResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xbf\x01\n\x13VerificationService\x12Z\n\x11VerifyTransaction\x12!.verification.VerificationRequest\x1a\".verification.VerificationResponse\x12L\n\tInitOrder\x12\x1e.verification.InitOrderRequest\x1a\x1f.verification.InitOrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_verification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERIFICATIONREQUEST']._serialized_start=75
  _globals['_VERIFICATIONREQUEST']._serialized_end=114
  _globals['_VERIFICATIONRESPONSE']._serialized_start=116
  _globals['_VERIFICATIONRESPONSE']._serialized_end=199
  _globals['_INITORDERREQUEST']._serialized_start=201
  _globals['_INITORDERREQUEST']._serialized_end=257
  _globals['_INITORDERRESPONSE']._serialized_start=259
  _globals['_INITORDERRESPONSE']._serialized_end=294
  _globals['_VERIFICATIONSERVICE']._serialized_start=297
  _globals['_VERIFICATIONSERVICE']._serialized_end=488
# @@protoc_insertion_point(module_scope)
