# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executor/executor.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from order_data import order_pb2 as order__data_dot_order__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x65xecutor/executor.proto\x12\x08\x65xecutor\x1a\x16order_data/order.proto\"\x10\n\x0e\x44\x65queueRequest\",\n\x15LeaderElectionRequest\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\">\n\x16LeaderElectionResponse\x12\x11\n\tleader_id\x18\x01 \x01(\t\x12\x11\n\tis_leader\x18\x02 \x01(\x08\"\x14\n\x12HealthCheckRequest\"\'\n\x13HealthCheckResponse\x12\x10\n\x08is_alive\x18\x01 \x01(\x08\x32\xe4\x01\n\rOrderExecutor\x12\x35\n\x07\x44\x65queue\x12\x18.executor.DequeueRequest\x1a\x10.order.OrderData\x12P\n\x0b\x45lectLeader\x12\x1f.executor.LeaderElectionRequest\x1a .executor.LeaderElectionResponse\x12J\n\x0bHealthCheck\x12\x1c.executor.HealthCheckRequest\x1a\x1d.executor.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'executor.executor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DEQUEUEREQUEST']._serialized_start=61
  _globals['_DEQUEUEREQUEST']._serialized_end=77
  _globals['_LEADERELECTIONREQUEST']._serialized_start=79
  _globals['_LEADERELECTIONREQUEST']._serialized_end=123
  _globals['_LEADERELECTIONRESPONSE']._serialized_start=125
  _globals['_LEADERELECTIONRESPONSE']._serialized_end=187
  _globals['_HEALTHCHECKREQUEST']._serialized_start=189
  _globals['_HEALTHCHECKREQUEST']._serialized_end=209
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=211
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=250
  _globals['_ORDEREXECUTOR']._serialized_start=253
  _globals['_ORDEREXECUTOR']._serialized_end=481
# @@protoc_insertion_point(module_scope)
