# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from executor import executor_pb2 as executor_dot_executor__pb2
from order_data import order_pb2 as order__data_dot_order__pb2


class OrderExecutorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Dequeue = channel.unary_unary(
                '/executor.OrderExecutor/Dequeue',
                request_serializer=executor_dot_executor__pb2.DequeueRequest.SerializeToString,
                response_deserializer=order__data_dot_order__pb2.OrderData.FromString,
                )
        self.ElectLeader = channel.unary_unary(
                '/executor.OrderExecutor/ElectLeader',
                request_serializer=executor_dot_executor__pb2.LeaderElectionRequest.SerializeToString,
                response_deserializer=executor_dot_executor__pb2.LeaderElectionResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/executor.OrderExecutor/HealthCheck',
                request_serializer=executor_dot_executor__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=executor_dot_executor__pb2.HealthCheckResponse.FromString,
                )


class OrderExecutorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Dequeue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ElectLeader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderExecutorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Dequeue': grpc.unary_unary_rpc_method_handler(
                    servicer.Dequeue,
                    request_deserializer=executor_dot_executor__pb2.DequeueRequest.FromString,
                    response_serializer=order__data_dot_order__pb2.OrderData.SerializeToString,
            ),
            'ElectLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.ElectLeader,
                    request_deserializer=executor_dot_executor__pb2.LeaderElectionRequest.FromString,
                    response_serializer=executor_dot_executor__pb2.LeaderElectionResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=executor_dot_executor__pb2.HealthCheckRequest.FromString,
                    response_serializer=executor_dot_executor__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'executor.OrderExecutor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrderExecutor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Dequeue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/executor.OrderExecutor/Dequeue',
            executor_dot_executor__pb2.DequeueRequest.SerializeToString,
            order__data_dot_order__pb2.OrderData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ElectLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/executor.OrderExecutor/ElectLeader',
            executor_dot_executor__pb2.LeaderElectionRequest.SerializeToString,
            executor_dot_executor__pb2.LeaderElectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/executor.OrderExecutor/HealthCheck',
            executor_dot_executor__pb2.HealthCheckRequest.SerializeToString,
            executor_dot_executor__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
